services:
    cinepro-core:
        build: .
        ports:
            - '3000:3000'
        environment:
            - HOST=0.0.0.0
            - PORT=3000
            - NODE_ENV=production
            - TMDB_API_KEY=${TMDB_API_KEY}
            - TMDB_CACHE_TTL=86400
            - CACHE_TYPE=memory
        restart: unless-stopped
        networks:
            - omss-network

networks:
    omss-network:
        driver: bridge
